version: "3.7"

services:
  gateway:
    build:
      dockerfile: $PWD/Dockerfile.service
      context: ./gateway
    command:
      - -logtostderr
    ports:
      - "8081:8081"
    restart: on-failure
    environment:
      GATEWAY_PORT: "8081"
      ENDPOINT_PORT: "editorservice:9090"
      HEALTH_ENDPOINT: "healthservice:9090"

  editorservice:
    build:
      dockerfile: $PWD/Dockerfile.service
      context: ./editorservice
    command:
      - -logtostderr
    restart: on-failure
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-editor_usr}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "${POSTGRES_DB:-editor}"

      SERVICE_PORT: "9090"

      CONSUL_HTTP_ADDR: "consul:8500"

  health:
    build:
      dockerfile: $PWD/Dockerfile.service
      context: ./healthservice
    restart: on-failure
    command:
      - -logtostderr
    environment:
      CONSUL_HTTP_ADDR: "consul:8500"

      SERVICE_PORT: "9090"

  db:
    image: "postgres:13"
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-editor}"
      POSTGRES_USER: "${POSTGRES_USER:-editor_usr}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"

  migration:
    build:
      dockerfile: Dockerfile.migration
      context: ./editorservice
    volumes:
      - "./:/workspace"
    command:
      - migrate
      - --database
      - "${POSTGRES_DB:-editor}"
      - --user
      - "${POSTGRES_USER:-editor_usr}"
      - --password
      - "${POSTGRES_PASSWORD:-password}"
      - --port
      - "5432"
      - --migrations
      - "editorservice/migrations"
      - --host
      - "db"
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-editor}"
      POSTGRES_USER: "${POSTGRES_USER:-editor_usr}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"

  consul:
    image: "consul:1.8"
    ports:
      - "8500:8500"
