FROM golang:1.14 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY pb/ pb/

COPY *.go ./

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o service .

FROM scratch

WORKDIR /app

COPY --from=builder /app/service /app/service

ENTRYPOINT ["/app/service"]

