FROM golang:1.14 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY pb/ pb/

COPY ./gateway/main.go ./gateway/main.go


RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o gateway github.com/nick96/cycad/editorservice/gateway

FROM scratch

WORKDIR /app

COPY --from=builder /app/gateway/gateway /app/gateway

ENTRYPOINT ["/app/gateway"]

